export const wtData = [
  {
    id: "RW5aUPJ0Ksc",
    firstName: "Maranda",
    lastName: "Brown",
    location: "Covington, Ga.",
    majors: "International affairs major; sociology and anthropology minor",
    afterGrad: "Brown will work in education and begin applying to law school.",
  },
  {
    id: "p8C5PfvX0WU",
    firstName: "Olivia",
    lastName: "Cianciolo",
    location: "Anderson, S.C.",
    majors: "Government major; international affairs minor; American politics concentration",
    afterGrad: "Cianciolo will attend law school at the University of South Carolina School of Law.",
  },
  {
    id: "WFJOrR9oflg",
    firstName: "Charlie",
    lastName: "Corbet",
    location: "Raleigh, N.C.",
    firstName2: "Jude",
    lastName2: "Walker",
    location2: "North Augusta, S.C.",
    majors: "Biology major",
    afterGrad: "Corbett (left) and Walker will attend dental school at the Medical University of South Carolina.",
  },
  {
    id: "kHQWvvM-TT4",
    firstName: "Tae’Von",
    lastName: "Gibbs",
    location: "Louisville, Ky.",
    majors: "Humanities major; environmental studies, film and digital media, and theatre minors",
    afterGrad: "Gibbs is moving to New York City to work with Teach for America.",
  },
  {
    id: "EYyKWfkBngM",
    firstName: "Sara",
    lastName: "Burns Gibson",
    location: "Walterboro, S.C.",
    majors: "Computer science and Spanish double major",
    afterGrad: "Gibson begins a position as a software engineer with Microsoft.",
  },
  {
    id: "ZeYKwBGLVWE",
    firstName: "Maggie",
    lastName: "Jackson",
    location: "Tallulah Falls, Ga.",
    majors: "Art history and physics double major; mathematics minor",
    afterGrad: "After a summer internship with McMillan Pazdan Smith in Spartanburg, Jackson will begin the Master of Architecture program at Clemson University.",
  },
  {
    id: "OkgOSvlNeaA",
    firstName: "Tianna",
    lastName: "Kidd",
    location: "Greenwood, S.C.",
    majors: "Biology and French double major; Francophone studies minor",
    afterGrad: "Kidd begins a Master of Science program at Wake Forest University and will conduct rotavirus research.",
  },
  {
    id: "wiL0DQi274Q",
    firstName: "Yohanna",
    lastName: "Peralta",
    location: "Greenville, S.C.",
    majors: "Accounting, finance and French triple major",
    afterGrad: "Peralta joins the PwC team in Spartanburg as a tax associate.",
  },
  {
    id: "T2HUR9b83Zo",
    firstName: "Walker",
    lastName: "Ramseur",
    location: "Raleigh, N.C.",
    majors: "Psychology major",
    afterGrad: "Ramseur begins a Master of Nursing program at Duke University.",
  },
  {
    id: "BDCUifrGStQ",
    firstName: "Diego",
    lastName: "Reyes",
    location: "Boca Raton, Fla.",
    majors: "Computer science and finance double major; accounting minor",
    afterGrad: "Reyes is moving to New York City, where he will work for Goldman Sachs as a software engineer.",
  },
  {
    id: "NGjfxsRJbdg",
    firstName: "Graham",
    lastName: "Segars",
    location: "Lexington, S.C.",
    majors: "Environmental studies major; international affairs minor",
    afterGrad: "Segars begins a Master of Science in sustainable business at the University of Miami.",
  },
  {
    id: "pKhYFtfQo5k",
    firstName: "Julia",
    lastName: "Slaughter",
    location: "Roebuck, S.C.",
    majors: "Biology major; pre-veterinary science program",
    afterGrad: "Slaughter commissioned through ROTC as a second lieutenant in the U.S. Army. She’s taking an educational delay to study veterinary medicine at South Dakota State University.",
  },
  // {
  //   id: "Jw9qNOG5Yz8",
  //   firstName: "Katie",
  //   lastName: "Sullivan",
  //   location: "",
  //   majors: "",
  //   afterGrad: "",
  // },
  {
    id: "tj9t8c6LckU",
    firstName: "Gabriel",
    lastName: "Tawiah",
    location: "Accra, Ghana",
    majors: "Economics and sociology and anthropology double major",
    afterGrad: "Tawiah, who has worked with Bank of America for the past two summers, will be moving to New York City to begin a career with the company.",
  },
  {
    id: "uNajXnL5KIw",
    firstName: "Grant",
    lastName: "Witherspoon",
    location: "Indian Land, S.C.",
    majors: "Biology and sociology and anthropology double major",
    afterGrad: "Witherspoon begins optometry school at Massachusetts College of Pharmacy and Health Sciences.",
  },
  {
    id: "wo9PPUOBw6k",
    firstName: "Charlie",
    lastName: "Yang",
    location: "Spartanburg, S.C.",
    majors: "Psychology and sociology and anthropology double major; gender studies concentration",
    afterGrad: "Yang plans to enter the workforce to gain experience before beginning a graduate program in human resources at the Darla Moore School of Business at the University of South Carolina.",
  },
  {
    id: "QyTCguiXIKw",
    firstName: "Kleo",
    lastName: "Young",
    location: "Anderson, S.C.",
    majors: "Biology and chemistry double major",
    afterGrad: "Young plans to work for a few years before considering a doctoral program in chemistry.",
  },
];
